# Copyright 2026 Pex project contributors.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "python-proxy"
edition = { workspace = true }
publish = false

[[bin]]
name = "python-proxy"
path = "src/bin/main.rs"

[[bin]]
name = "python-proxyw"
path = "src/bin/mainw.rs"
required-features = ["windows"]

[dependencies]
anyhow = { workspace = true }
cache = { path = "../cache" }
pex = { path = "../pex" }
platform = { path = "../platform" }
target = { path = "../target" }
zip = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = ["Win32_UI_WindowsAndMessaging"] }

[features]
windows = []