# Copyright 2026 Pex project contributors.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "repackage"
edition = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
fs-err = { workspace = true }
logging_timer = { workspace = true }
ouroboros = { workspace = true }
pex = { path = "../pex" }
platform = { path = "../platform" }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
wheel = { path = "../wheel" }
zip = { workspace = true }
