# Copyright 2026 Pex project contributors.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "logging"
edition = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
env_filter = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tracing-chrome = { workspace = true }
tracing-subscriber = { workspace = true }
