# Copyright 2026 Pex project contributors.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "logging"
edition = { workspace = true }
publish = false

[dependencies]
anstream = { workspace = true }
anyhow = { workspace = true }
env_filter = { workspace = true }
fs-err = { workspace = true }
log = { workspace = true }
owo-colors = { workspace = true }
tracing-subscriber = {  version = "0.3", features = ["time"] }

# profiling feature deps
tracing-chrome = {  version = "0.7", optional = true }
tracing-flame = { version = "0.2", optional = true }

[features]
profiling = [
    "dep:tracing-chrome",
    "dep:tracing-flame",
]